#define IDH_IDOK                           1
#define IDH_IDCANCEL                       2
#define IDH_IDHELP                         9
#define IDH_NUFXLIB_VERS_TEXT           1001
#define IDH_CONTENT_LIST                1002
#define IDH_COL_PATHNAME                1005
#define IDH_COL_TYPE                    1006
#define IDH_COL_AUXTYPE                 1007
#define IDH_COL_MODDATE                 1008
#define IDH_COL_FORMAT                  1009
#define IDH_COL_SIZE                    1010
#define IDH_COL_RATIO                   1011
#define IDH_COL_PACKED                  1012
#define IDH_COL_ACCESS                  1013
#define IDH_COL_DEFAULTS                1014
#define IDH_DEFC_UNCOMPRESSED           1016
#define IDH_DEFC_SQUEEZE                1017
#define IDH_DEFC_LZW1                   1018
#define IDH_DEFC_LZW2                   1019
#define IDH_DEFC_LZC12                  1020
#define IDH_DEFC_LZC16                  1021
#define IDH_DEFC_DEFLATE                1022
#define IDH_DEFC_BZIP2                  1023
#define IDH_TOPIC1024                   1024
#define IDH_PVIEW_NOWRAP_TEXT           1025
#define IDH_PVIEW_BOLD_HEXDUMP          1026
#define IDH_PVIEW_BOLD_BASIC            1027
#define IDH_PVIEW_DISASM_ONEBYTEBRKCOP  1028
#define IDH_PVIEW_HIRES_BW              1029
#define IDH_PVIEW_DHR_CONV_COMBO        1030
#define IDH_PVIEW_MOUSETEXT_TO_ASCII    1031
#define IDH_PVIEW_HITEXT                1036
#define IDH_PVIEW_PASCALTEXT            1037
#define IDH_PVIEW_APPLESOFT             1038
#define IDH_PVIEW_INTEGER               1039
#define IDH_PVIEW_HIRES                 1040
#define IDH_PVIEW_DHR                   1041
#define IDH_PVIEW_SHR                   1042
#define IDH_PVIEW_AWP                   1043
#define IDH_PVIEW_PRODOSFOLDER          1044
#define IDH_PVIEW_RESOURCES             1045
#define IDH_PVIEW_RELAX_GFX             1046
#define IDH_PVIEW_ADB                   1047
#define IDH_PVIEW_SCASSEM               1048
#define IDH_PVIEW_ASP                   1049
#define IDH_PVIEW_MACPAINT              1050
#define IDH_PVIEW_PASCALCODE            1051
#define IDH_PVIEW_CPMTEXT               1052
#define IDH_PVIEW_GWP                   1053
#define IDH_PVIEW_DISASM                1054
#define IDH_PVIEW_PRINTSHOP             1055
#define IDH_PVIEW_TEXT8                 1056
#define IDH_PVIEW_SIZE_EDIT             1060
#define IDH_PVIEW_SIZE_SPIN             1061
#define IDH_DISKEDIT_DOREAD             1063
#define IDH_DISKEDIT_DOWRITE            1064
#define IDH_DISKEDIT_TRACK              1065
#define IDH_DISKEDIT_TRACKSPIN          1066
#define IDH_DISKEDIT_SECTOR             1067
#define IDH_DISKEDIT_SECTORSPIN         1068
#define IDH_DISKEDIT_OPENFILE           1069
#define IDH_DISKEDIT_EDIT               1070
#define IDH_DISKEDIT_PREV               1071
#define IDH_DISKEDIT_NEXT               1072
#define IDH_STEXT_SECTOR                1073
#define IDH_STEXT_TRACK                 1074
#define IDH_DISKEDIT_DONE               1077
#define IDH_DISKEDIT_HEX                1078
#define IDH_DISKEDIT_SUBVOLUME          1081
#define IDH_TOPIC1082                   1082
#define IDH_TOPIC1089                   1089
#define IDH_DECONF_FSFORMAT             1090
#define IDH_DECONF_SECTORORDER          1091
#define IDH_DECONF_PHYSICAL             1092
#define IDH_DECONF_FILEFORMAT           1093
#define IDH_DECONF_SOURCE               1094
#define IDH_DISKIMG_VERS_TEXT           1095
#define IDH_FVIEW_EDITBOX               1101
#define IDH_SELECTED_COUNT              1102
#define IDH_TOPIC1103                   1103
#define IDH_TOPIC1105                   1105
#define IDH_DECONF_HELP                 1112
#define IDH_SUBV_LIST                   1114
#define IDH_DEFILE_FILENAME             1115
#define IDH_DEFILE_RSRC                 1116
#define IDH_CIDERPRESS_VERS_TEXT        1117
#define IDH_PREF_TEMP_FOLDER            1118
#define IDH_CHOOSEDIR_TREE              1121
#define IDH_CHOOSEDIR_PATHEDIT          1123
#define IDH_CHOOSEDIR_EXPAND_TREE       1124
#define IDH_CHOOSEDIR_PATH              1125
#define IDH_CHOOSEDIR_NEW_FOLDER        1127
#define IDH_PREF_CHOOSE_TEMP_FOLDER     1128
#define IDH_FVIEW_FONT                  1129
#define IDH_FVIEW_NEXT                  1130
#define IDH_FVIEW_PREV                  1131
#define IDH_NEWFOLDER_CURDIR            1132
#define IDH_NEWFOLDER_NAME              1133
#define IDH_EXT_PATH                    1136
#define IDH_EXT_CONVEOLTEXT             1137
#define IDH_EXT_CONVEOLALL              1138
#define IDH_EXT_STRIP_FOLDER            1142
#define IDH_EXT_OVERWRITE_EXIST         1143
#define IDH_EXT_SELECTED                1144
#define IDH_EXT_ALL                     1145
#define IDH_EXT_REFORMAT                1147
#define IDH_EXT_DATAFORK                1148
#define IDH_EXT_RSRCFORK                1149
#define IDH_EXT_CONVEOLNONE             1151
#define IDH_EXT_CHOOSE_FOLDER           1152
#define IDH_PROG_ARC_NAME               1153
#define IDH_PROG_FILE_NAME              1154
#define IDH_PROG_VERB                   1155
#define IDH_PROG_TOFROM                 1156
#define IDH_PROG_PROGRESS               1157
#define IDH_OVWR_YES                    1161
#define IDH_OVWR_YESALL                 1162
#define IDH_OVWR_NO                     1163
#define IDH_OVWR_NOALL                  1164
#define IDH_OVWR_NEW_INFO               1166
#define IDH_OVWR_RENAME                 1167
#define IDH_OVWR_EXIST_NAME             1168
#define IDH_OVWR_EXIST_INFO             1169
#define IDH_OVWR_NEW_NAME               1170
#define IDH_RENOVWR_SOURCE_NAME         1171
#define IDH_RENOVWR_ORIG_NAME           1172
#define IDH_RENOVWR_NEW_NAME            1173
#define IDH_SELECT_ACCEPT               1175
#define IDH_ADDFILES_PREFIX             1177
#define IDH_ADDFILES_INCLUDE_SUBFOLDERS 1180
#define IDH_ADDFILES_STRIP_FOLDER       1181
#define IDH_ADDFILES_NOPRESERVE         1182
#define IDH_ADDFILES_PRESERVE           1183
#define IDH_ADDFILES_PRESERVEPLUS       1184
#define IDH_ADDFILES_STATIC1            1186
#define IDH_ADDFILES_STATIC2            1187
#define IDH_ADDFILES_STATIC3            1188
#define IDH_ADDFILES_OVERWRITE          1189
#define IDH_PREF_SHRINKIT_COMPAT        1190
#define IDH_USE_SELECTED                1192
#define IDH_USE_ALL                     1193
#define IDH_RENAME_OLD                  1194
#define IDH_RENAME_NEW                  1195
#define IDH_RENAME_PATHSEP              1196
#define IDH_COMMENT_EDIT                1198
#define IDH_COMMENT_DELETE              1199
#define IDH_RECOMP_COMP                 1201
#define IDH_PREF_ASSOCIATIONS           1202
#define IDH_ASSOCIATION_LIST            1209
#define IDH_REG_COMPANY_NAME            1210
#define IDH_REG_EXPIRES                 1211
#define IDH_ABOUT_ENTER_REG             1212
#define IDH_REGENTER_USER               1213
#define IDH_REGENTER_COMPANY            1214
#define IDH_REGENTER_REG                1215
#define IDH_REG_USER_NAME               1216
#define IDH_ZLIB_VERS_TEXT              1218
#define IDH_EXT_CONVHIGHASCII           1219
#define IDH_EXT_DISKIMAGE               1220
#define IDH_EXT_DISK_2MG                1221
#define IDH_EXT_ADD_PRESERVE            1222
#define IDH_EXT_ADD_EXTEN               1223
#define IDH_EXT_CONFIG_PRESERVE         1224
#define IDH_EXT_CONFIG_CONVERT          1225
#define IDH_PREF_COERCE_DOS             1226
#define IDH_PREF_SPACES_TO_UNDER        1227
#define IDH_REGENTER_USERCRC            1228
#define IDH_REGENTER_COMPCRC            1229
#define IDH_REGENTER_REGCRC             1230
#define IDH_RENAME_SKIP                 1232
#define IDH_DECONF_VIEWASBLOCKS         1233
#define IDH_DECONF_VIEWASSECTORS        1234
#define IDH_DECONF_VIEWASNIBBLES        1235
#define IDH_DECONF_OUTERFORMAT          1236
#define IDH_DECONF_VIEWAS               1237
#define IDH_IMAGE_TYPE                  1238
#define IDH_DISKCONV_DOS                1239
#define IDH_DISKCONV_DOS2MG             1240
#define IDH_DISKCONV_PRODOS             1241
#define IDH_DISKCONV_PRODOS2MG          1242
#define IDH_DISKCONV_NIB                1243
#define IDH_DISKCONV_NIB2MG             1244
#define IDH_DISKCONV_D13                1245
#define IDH_DISKCONV_DC42               1246
#define IDH_DISKCONV_SDK                1247
#define IDH_DISKCONV_TRACKSTAR          1248
#define IDH_DISKCONV_HDV                1249
#define IDH_DISKCONV_DDD                1250
#define IDH_DISKCONV_GZIP               1251
#define IDH_DISKEDIT_NIBBLE_PARMS       1252
#define IDH_PROPS_PATHNAME              1255
#define IDH_PROPS_FILETYPE              1256
#define IDH_PROPS_AUXTYPE               1257
#define IDH_PROPS_ACCESS_R              1258
#define IDH_PROPS_ACCESS_W              1259
#define IDH_PROPS_ACCESS_N              1260
#define IDH_PROPS_ACCESS_D              1261
#define IDH_PROPS_ACCESS_I              1262
#define IDH_PROPS_ACCESS_B              1263
#define IDH_PROPS_MODWHEN               1266
#define IDH_PROPS_TYPEDESCR             1267
#define IDH_TOPIC1269                   1269
#define IDH_CONVFILE_PRESERVEDIR        1270
#define IDH_CONVDISK_140K               1271
#define IDH_CONVDISK_800K               1273
#define IDH_CONVDISK_1440K              1274
#define IDH_CONVDISK_5MB                1275
#define IDH_CONVDISK_16MB               1276
#define IDH_CONVDISK_20MB               1277
#define IDH_CONVDISK_32MB               1278
#define IDH_CONVDISK_SPECIFY            1279
#define IDH_IMAGE_SIZE_TEXT             1289
#define IDH_BULKCONV_PATHNAME           1290
#define IDH_PREF_EXTVIEWER_EXTS         1292
#define IDH_VOLUME_LIST                 1295
#define IDH_OPENVOL_READONLY            1296
#define IDH_VOLUMECOPYPROG_FROM         1297
#define IDH_VOLUMECOPYPROG_TO           1298
#define IDH_VOLUMECOPYPROG_PROGRESS     1299
#define IDH_CONVDISK_SPECIFY_EDIT       1302
#define IDH_CONVDISK_COMPUTE            1303
#define IDH_DEOW_FILE                   1303
#define IDH_CONVDISK_SPACEREQ           1304
#define IDH_DEOW_VOLUME                 1304
#define IDH_DEOW_CURRENT                1305
#define IDH_TOPIC1306                   1306
#define IDH_CONVDISK_VOLNAME            1307
#define IDH_VOLUME_FILTER               1307
#define IDH_VOLUMECOPYSEL_LIST          1309
#define IDH_VOLUEMCOPYSEL_TOFILE        1310
#define IDH_VOLUEMCOPYSEL_FROMFILE      1311
#define IDH_CREATEFS_DOS32              1312
#define IDH_CREATEFS_DOS33              1313
#define IDH_CREATEFS_PRODOS             1314
#define IDH_CREATEFS_PASCAL             1315
#define IDH_CREATEFS_HFS                1316
#define IDH_CREATEFS_BLANK              1317
#define IDH_TOPIC1320                   1320
#define IDH_CREATEFSDOS_ALLOCDOS        1321
#define IDH_CREATEFSDOS_VOLNUM          1322
#define IDH_CREATEFSPRODOS_VOLNAME      1323
#define IDH_CREATEFSPASCAL_VOLNAME      1324
#define IDH_ASPI_VERS_TEXT              1330
#define IDH_PREF_SUCCESS_BEEP           1331
#define IDH_ADD_TARGET_TREE             1333
#define IDH_AIDISK_SUBVOLSEL            1334
#define IDH_AIDISK_NOTES                1335
#define IDH_AI_FILENAME                 1336
#define IDH_AIBNY_RECORDS               1337
#define IDH_AINUFX_FORMAT               1338
#define IDH_AINUFX_RECORDS              1339
#define IDH_AINUFX_MASTERVERSION        1340
#define IDH_AINUFX_CREATEWHEN           1341
#define IDH_AINUFX_MODIFYWHEN           1342
#define IDH_AINUFX_JUNKSKIPPED          1343
#define IDH_AIDISK_OUTERFORMAT          1344
#define IDH_AIDISK_FILEFORMAT           1345
#define IDH_AIDISK_PHYSICALFORMAT       1346
#define IDH_AIDISK_SECTORORDER          1347
#define IDH_AIDISK_FSFORMAT             1348
#define IDH_AIDISK_FILECOUNT            1349
#define IDH_AIDISK_CAPACITY             1350
#define IDH_AIDISK_FREESPACE            1351
#define IDH_AIDISK_DAMAGED              1352
#define IDH_AIDISK_WRITEABLE            1354
#define IDH_PDISK_CONFIRM_FORMAT        1359
#define IDH_PDISK_PRODOS_ALLOWLOWER     1360
#define IDH_PDISK_PRODOS_USESPARSE      1361
#define IDH_FVIEW_PRINT                 1363
#define IDH_CREATESUBDIR_BASE           1364
#define IDH_CREATESUBDIR_NEW            1365
#define IDH_RENAMEVOL_TREE              1366
#define IDH_RENAMEVOL_NEW               1367
#define IDH_ADDFILES_CONVEOLNONE        1368
#define IDH_ADDFILES_CONVEOLTEXT        1369
#define IDH_ADDFILES_CONVEOLALL         1370
#define IDH_ADDFILES_STATIC4            1371
#define IDH_PROPS_CREATEWHEN            1372
#define IDH_EOLSCAN_CR                  1374
#define IDH_EOLSCAN_LF                  1375
#define IDH_EOLSCAN_CRLF                1376
#define IDH_EOLSCAN_CHARS               1377
#define IDH_PREF_PASTE_JUNKPATHS        1378
#define IDH_EXT_CONVEOLTYPE             1379
#define IDH_ADDFILES_CONVEOLTYPE        1380
#define IDH_TWOIMG_LOCKED               1381
#define IDH_TWOIMG_DOSVOLSET            1382
#define IDH_TWOIMG_DOSVOLNUM            1383
#define IDH_TWOIMG_COMMENT              1384
#define IDH_TWOIMG_CREATOR              1385
#define IDH_TWOIMG_VERSION              1386
#define IDH_TWOIMG_FORMAT               1387
#define IDH_TWOIMG_BLOCKS               1388
#define IDH_FVIEW_DATA                  1395
#define IDH_FVIEW_RSRC                  1396
#define IDH_FVIEW_CMMT                  1397
#define IDH_FVIEW_FORMATSEL             1399
#define IDH_FVIEW_FMT_HEX               1400
#define IDH_FVIEW_FMT_RAW               1401
#define IDH_FVIEW_FMT_BEST              1403
#define IDH_PDISK_OPENVOL_RO            1405
#define IDH_EOLSCAN_HIGHASCII           1407
#define IDH_CASSETTE_LIST               1414
#define IDH_IMPORT_CHUNK                1416
#define IDH_CASSETTE_ALG                1418
#define IDH_CASSETTE_INPUT              1419
#define IDH_CASSIMPTARG_FILENAME        1420
#define IDH_CASSIMPTARG_BAS             1421
#define IDH_CASSIMPTARG_INT             1422
#define IDH_CASSIMPTARG_BIN             1423
#define IDH_CASSIMPTARG_BINADDR         1424
#define IDH_CASSIMPTARG_RANGE           1425
#define IDH_CLASH_RENAME                1426
#define IDH_CLASH_SKIP                  1427
#define IDH_CLASH_WINNAME               1428
#define IDH_CLASH_STORAGENAME           1429
#define IDH_PREF_REDUCE_SHK_ERROR_CHECKS 1430
#define IDH_IMPORT_BAS_RESULTS          1431
#define IDH_IMPORT_BAS_SAVEAS           1432
#define IDH_FVIEW_FIND                  1438
#define IDH_CREATEFSHFS_VOLNAME         1440
#define IDH_PROPS_HFS_FILETYPE          1441
#define IDH_PROPS_HFS_AUXTYPE           1442
#define IDH_PROPS_HFS_MODE              1444
#define IDH_PROPS_HFS_LABEL             1445
#define IDH_PASTE_SPECIAL_COUNT         1446
#define IDH_PASTE_SPECIAL_PATHS         1447
#define IDH_PASTE_SPECIAL_NOPATHS       1448
#define IDH_PROGRESS_COUNTER_COUNT      1449
#define IDH_PROGRESS_COUNTER_DESC       1450
#define IDH_PDISK_OPENVOL_PHYS0         1451
#define IDH_PREF_SHK_BAD_MAC            1453
