//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CiderPress.rc
//
#define IDR_MAINFRAME                   102
#define IDD_ABOUTDLG                    105
#define IDB_FSLOGO                      106
#define IDR_TOOLBAR1                    107
#define IDI_FILE_NUFX                   108
#define IDI_FILE_BINARY2                109
#define IDI_FILE_DISKIMAGE              110
#define IDB_HDRBAR                      110
#define IDD_PREF_GENERAL                115
#define IDD_PREF_COMPRESSION            116
#define IDR_RIGHTCLICKMENU              117
#define IDD_FILE_VIEWER                 118
#define IDI_FILE_VIEWER                 120
#define IDD_PREF_FVIEW                  121
#define IDB_LIST_PICS                   123
#define IDD_DISKEDIT                    127
#define IDD_DECONF                      128
#define IDD_SUBV                        131
#define IDD_DEFILE                      132
#define IDD_PREF_FILES                  133
#define IDB_NEW_FOLDER                  139
#define IDB_CHOOSE_FOLDER               140
#define IDD_EXTRACT_FILES               142
#define IDD_ACTION_PROGRESS             143
#define IDD_CONFIRM_OVERWRITE           144
#define IDD_RENAME_OVERWRITE            145
#define IDD_USE_SELECTION               147
#define IDD_RENAME_ENTRY                148
#define IDD_COMMENT_EDIT                149
#define IDD_RECOMPRESS_OPTS             150
#define IDD_PRINT_CANCEL                152
#define IDD_ASSOCIATIONS                153
#define IDD_REGISTRATION                157
#define IDD_DISKCONV                    158
#define IDD_DONEOPEN                    159
#define IDD_PROPS_EDIT                  160
#define IDD_CONVFILE_OPTS               161
#define IDD_CONVDISK_OPTS               162
#define IDD_BULKCONV                    163
#define IDD_OPENVOLUMEDLG               164
#define IDD_VOLUMECOPYPROG              166
#define IDD_DISKEDIT_OPENWHICH          167
#define IDD_VOLUMECOPYSEL               169
#define IDB_VOL_PICS                    170
#define IDD_FORMATTING                  171
#define IDD_CREATEIMAGE                 172
#define IDD_CHOOSE_ADD_TARGET           173
#define IDB_TREE_PICS                   174
#define IDD_ARCHIVEINFO_NUFX            175
#define IDD_ARCHIVEINFO_DISK            176
#define IDD_ARCHIVEINFO_BNY             177
#define IDD_PREF_DISKIMAGE              178
#define IDD_CREATE_SUBDIR               179
#define IDD_RENAME_VOLUME               180
#define IDD_EOLSCAN                     181
#define IDD_TWOIMG_PROPS                182
#define IDD_LOADING                     183
#define IDD_IMPORTCASSETTE              184
#define IDD_CASSIMPTARGET               186
#define IDD_ADD_CLASH                   187
#define IDD_ARCHIVEINFO_ACU             188
#define IDD_IMPORT_BAS                  189
#define IDD_PASTE_SPECIAL               190
#define IDD_PROGRESS_COUNTER            191
#define IDD_ARCHIVEINFO_APPLESINGLE     192
#define IDC_NUFXLIB_VERS_TEXT           1001
#define IDC_CONTENT_LIST                1002
#define IDC_COL_PATHNAME                1005
#define IDC_COL_TYPE                    1006
#define IDC_COL_AUXTYPE                 1007
#define IDC_COL_MODDATE                 1008
#define IDC_COL_FORMAT                  1009
#define IDC_COL_SIZE                    1010
#define IDC_COL_RATIO                   1011
#define IDC_COL_PACKED                  1012
#define IDC_COL_ACCESS                  1013
#define IDC_COL_DEFAULTS                1014
#define IDC_DEFC_UNCOMPRESSED           1016
#define IDC_DEFC_SQUEEZE                1017
#define IDC_DEFC_LZW1                   1018
#define IDC_DEFC_LZW2                   1019
#define IDC_DEFC_LZC12                  1020
#define IDC_DEFC_LZC16                  1021
#define IDC_DEFC_DEFLATE                1022
#define IDC_DEFC_BZIP2                  1023
#define IDC_PVIEW_NOWRAP_TEXT           1025
#define IDC_PVIEW_BOLD_HEXDUMP          1026
#define IDC_PVIEW_BOLD_BASIC            1027
#define IDC_PVIEW_DISASM_ONEBYTEBRKCOP  1028
#define IDC_PVIEW_HIRES_BW              1029
#define IDC_PVIEW_DHR_CONV_COMBO        1030
#define IDC_PVIEW_MOUSETEXT_TO_ASCII    1031
#define IDC_PVIEW_HITEXT                1036
#define IDC_PVIEW_PASCALTEXT            1037
#define IDC_PVIEW_APPLESOFT             1038
#define IDC_PVIEW_INTEGER               1039
#define IDC_PVIEW_HIRES                 1040
#define IDC_PVIEW_DHR                   1041
#define IDC_PVIEW_SHR                   1042
#define IDC_PVIEW_AWP                   1043
#define IDC_PVIEW_PRODOSFOLDER          1044
#define IDC_PVIEW_RESOURCES             1045
#define IDC_PVIEW_RELAX_GFX             1046
#define IDC_PVIEW_ADB                   1047
#define IDC_PVIEW_SCASSEM               1048
#define IDC_PVIEW_ASP                   1049
#define IDC_PVIEW_MACPAINT              1050
#define IDC_PVIEW_PASCALCODE            1051
#define IDC_PVIEW_CPMTEXT               1052
#define IDC_PVIEW_GWP                   1053
#define IDC_PVIEW_DISASM                1054
#define IDC_PVIEW_PRINTSHOP             1055
#define IDC_PVIEW_TEXT8                 1056
#define IDC_PVIEW_SIZE_EDIT             1060
#define IDC_PVIEW_SIZE_SPIN             1061
#define IDC_DISKEDIT_DOREAD             1063
#define IDC_DISKEDIT_DOWRITE            1064
#define IDC_DISKEDIT_TRACK              1065
#define IDC_DISKEDIT_TRACKSPIN          1066
#define IDC_DISKEDIT_SECTOR             1067
#define IDC_DISKEDIT_SECTORSPIN         1068
#define IDC_DISKEDIT_OPENFILE           1069
#define IDC_DISKEDIT_EDIT               1070
#define IDC_DISKEDIT_PREV               1071
#define IDC_DISKEDIT_NEXT               1072
#define IDC_STEXT_SECTOR                1073
#define IDC_STEXT_TRACK                 1074
#define IDC_DISKEDIT_DONE               1077
#define IDC_DISKEDIT_HEX                1078
#define IDC_DISKEDIT_SUBVOLUME          1081
#define IDC_DECONF_FSFORMAT             1090
#define IDC_DECONF_SECTORORDER          1091
#define IDC_DECONF_PHYSICAL             1092
#define IDC_DECONF_FILEFORMAT           1093
#define IDC_DECONF_SOURCE               1094
#define IDC_DISKIMG_VERS_TEXT           1095
#define IDC_FVIEW_EDITBOX               1101
#define IDC_SELECTED_COUNT              1102
#define IDC_ABOUT_CREDITS               1111
#define IDC_DECONF_HELP                 1112
#define IDC_SUBV_LIST                   1114
#define IDC_DEFILE_FILENAME             1115
#define IDC_DEFILE_RSRC                 1116
#define IDC_CIDERPRESS_VERS_TEXT        1117
#define IDC_PREF_TEMP_FOLDER            1118
#define IDC_PREF_CHOOSE_TEMP_FOLDER     1128
#define IDC_FVIEW_FONT                  1129
#define IDC_FVIEW_NEXT                  1130
#define IDC_FVIEW_PREV                  1131
#define IDC_EXT_PATH                    1136
#define IDC_EXT_CONVEOLTEXT             1137
#define IDC_EXT_CONVEOLALL              1138
#define IDC_EXT_STRIP_FOLDER            1142
#define IDC_EXT_OVERWRITE_EXIST         1143
#define IDC_EXT_SELECTED                1144
#define IDC_EXT_ALL                     1145
#define IDC_EXT_REFORMAT                1147
#define IDC_EXT_DATAFORK                1148
#define IDC_EXT_RSRCFORK                1149
#define IDC_EXT_CONVEOLNONE             1151
#define IDC_EXT_CHOOSE_FOLDER           1152
#define IDC_PROG_ARC_NAME               1153
#define IDC_PROG_FILE_NAME              1154
#define IDC_PROG_VERB                   1155
#define IDC_PROG_TOFROM                 1156
#define IDC_PROG_PROGRESS               1157
#define IDC_OVWR_YES                    1161
#define IDC_OVWR_YESALL                 1162
#define IDC_OVWR_NO                     1163
#define IDC_OVWR_NOALL                  1164
#define IDC_OVWR_NEW_INFO               1166
#define IDC_OVWR_RENAME                 1167
#define IDC_OVWR_EXIST_NAME             1168
#define IDC_OVWR_EXIST_INFO             1169
#define IDC_OVWR_NEW_NAME               1170
#define IDC_RENOVWR_SOURCE_NAME         1171
#define IDC_RENOVWR_ORIG_NAME           1172
#define IDC_RENOVWR_NEW_NAME            1173
#define IDC_SELECT_ACCEPT               1175
#define IDC_ADDFILES_PREFIX             1177
#define IDC_ADDFILES_INCLUDE_SUBFOLDERS 1180
#define IDC_ADDFILES_STRIP_FOLDER       1181
#define IDC_ADDFILES_NOPRESERVE         1182
#define IDC_ADDFILES_PRESERVE           1183
#define IDC_ADDFILES_PRESERVEPLUS       1184
#define IDC_ADDFILES_STATIC1            1186
#define IDC_ADDFILES_STATIC2            1187
#define IDC_ADDFILES_STATIC3            1188
#define IDC_ADDFILES_OVERWRITE          1189
#define IDC_PREF_SHRINKIT_COMPAT        1190
#define IDC_USE_SELECTED                1192
#define IDC_USE_ALL                     1193
#define IDC_RENAME_OLD                  1194
#define IDC_RENAME_NEW                  1195
#define IDC_RENAME_PATHSEP              1196
#define IDC_COMMENT_EDIT                1198
#define IDC_COMMENT_DELETE              1199
#define IDC_RECOMP_COMP                 1201
#define IDC_PREF_ASSOCIATIONS           1202
#define IDC_ASSOCIATION_LIST            1209
#define IDC_REG_COMPANY_NAME            1210
#define IDC_REG_EXPIRES                 1211
#define IDC_ABOUT_ENTER_REG             1212
#define IDC_REGENTER_USER               1213
#define IDC_REGENTER_COMPANY            1214
#define IDC_REGENTER_REG                1215
#define IDC_REG_USER_NAME               1216
#define IDC_ZLIB_VERS_TEXT              1218
#define IDC_EXT_CONVHIGHASCII           1219
#define IDC_EXT_DISKIMAGE               1220
#define IDC_EXT_DISK_2MG                1221
#define IDC_EXT_ADD_PRESERVE            1222
#define IDC_EXT_ADD_EXTEN               1223
#define IDC_EXT_CONFIG_PRESERVE         1224
#define IDC_EXT_CONFIG_CONVERT          1225
#define IDC_PREF_COERCE_DOS             1226
#define IDC_PREF_SPACES_TO_UNDER        1227
#define IDC_REGENTER_USERCRC            1228
#define IDC_REGENTER_COMPCRC            1229
#define IDC_REGENTER_REGCRC             1230
#define IDC_RENAME_SKIP                 1232
#define IDC_DECONF_VIEWASBLOCKS         1233
#define IDC_DECONF_VIEWASSECTORS        1234
#define IDC_DECONF_VIEWASNIBBLES        1235
#define IDC_DECONF_OUTERFORMAT          1236
#define IDC_DECONF_VIEWAS               1237
#define IDC_IMAGE_TYPE                  1238
#define IDC_DISKCONV_DOS                1239
#define IDC_DISKCONV_DOS2MG             1240
#define IDC_DISKCONV_PRODOS             1241
#define IDC_DISKCONV_PRODOS2MG          1242
#define IDC_DISKCONV_NIB                1243
#define IDC_DISKCONV_NIB2MG             1244
#define IDC_DISKCONV_D13                1245
#define IDC_DISKCONV_DC42               1246
#define IDC_DISKCONV_SDK                1247
#define IDC_DISKCONV_TRACKSTAR          1248
#define IDC_DISKCONV_HDV                1249
#define IDC_DISKCONV_DDD                1250
#define IDC_DISKCONV_GZIP               1251
#define IDC_DISKEDIT_NIBBLE_PARMS       1252
#define IDC_PROPS_PATHNAME              1255
#define IDC_PROPS_FILETYPE              1256
#define IDC_PROPS_AUXTYPE               1257
#define IDC_PROPS_ACCESS_R              1258
#define IDC_PROPS_ACCESS_W              1259
#define IDC_PROPS_ACCESS_N              1260
#define IDC_PROPS_ACCESS_D              1261
#define IDC_PROPS_ACCESS_I              1262
#define IDC_PROPS_ACCESS_B              1263
#define IDC_PROPS_MODWHEN               1266
#define IDC_PROPS_TYPEDESCR             1267
#define IDC_CONVFILE_PRESERVEDIR        1270
#define IDC_CONVDISK_140K               1271
#define IDC_CONVDISK_800K               1273
#define IDC_CONVDISK_1440K              1274
#define IDC_CONVDISK_5MB                1275
#define IDC_CONVDISK_16MB               1276
#define IDC_CONVDISK_20MB               1277
#define IDC_CONVDISK_32MB               1278
#define IDC_CONVDISK_SPECIFY            1279
#define IDC_IMAGE_SIZE_TEXT             1289
#define IDC_BULKCONV_PATHNAME           1290
#define IDC_PREF_EXTVIEWER_EXTS         1292
#define IDC_VOLUME_LIST                 1295
#define IDC_OPENVOL_READONLY            1296
#define IDC_VOLUMECOPYPROG_FROM         1297
#define IDC_VOLUMECOPYPROG_TO           1298
#define IDC_VOLUMECOPYPROG_PROGRESS     1299
#define IDC_CONVDISK_SPECIFY_EDIT       1302
#define IDC_CONVDISK_COMPUTE            1303
#define IDC_DEOW_FILE                   1303
#define IDC_CONVDISK_SPACEREQ           1304
#define IDC_DEOW_VOLUME                 1304
#define IDC_DEOW_CURRENT                1305
#define IDC_CONVDISK_VOLNAME            1307
#define IDC_VOLUME_FILTER               1307
#define IDC_VOLUMECOPYSEL_LIST          1309
#define IDC_VOLUEMCOPYSEL_TOFILE        1310
#define IDC_VOLUEMCOPYSEL_FROMFILE      1311
#define IDC_CREATEFS_DOS32              1312
#define IDC_CREATEFS_DOS33              1313
#define IDC_CREATEFS_PRODOS             1314
#define IDC_CREATEFS_PASCAL             1315
#define IDC_CREATEFS_HFS                1316
#define IDC_CREATEFS_BLANK              1317
#define IDC_CREATEFSDOS_ALLOCDOS        1321
#define IDC_CREATEFSDOS_VOLNUM          1322
#define IDC_CREATEFSPRODOS_VOLNAME      1323
#define IDC_CREATEFSPASCAL_VOLNAME      1324
#define IDC_ASPI_VERS_TEXT              1330
#define IDC_PREF_SUCCESS_BEEP           1331
#define IDC_ADD_TARGET_TREE             1333
#define IDC_AIDISK_SUBVOLSEL            1334
#define IDC_AIDISK_NOTES                1335
#define IDC_AI_FILENAME                 1336
#define IDC_AIBNY_RECORDS               1337
#define IDC_AINUFX_FORMAT               1338
#define IDC_AINUFX_RECORDS              1339
#define IDC_AINUFX_MASTERVERSION        1340
#define IDC_AINUFX_CREATEWHEN           1341
#define IDC_AINUFX_MODIFYWHEN           1342
#define IDC_AINUFX_JUNKSKIPPED          1343
#define IDC_AIDISK_OUTERFORMAT          1344
#define IDC_AIDISK_FILEFORMAT           1345
#define IDC_AIDISK_PHYSICALFORMAT       1346
#define IDC_AIDISK_SECTORORDER          1347
#define IDC_AIDISK_FSFORMAT             1348
#define IDC_AIDISK_FILECOUNT            1349
#define IDC_AIDISK_CAPACITY             1350
#define IDC_AIDISK_FREESPACE            1351
#define IDC_AIDISK_DAMAGED              1352
#define IDC_AIDISK_WRITEABLE            1354
#define IDC_PDISK_CONFIRM_FORMAT        1359
#define IDC_PDISK_PRODOS_ALLOWLOWER     1360
#define IDC_PDISK_PRODOS_USESPARSE      1361
#define IDC_FVIEW_PRINT                 1363
#define IDC_CREATESUBDIR_BASE           1364
#define IDC_CREATESUBDIR_NEW            1365
#define IDC_RENAMEVOL_TREE              1366
#define IDC_RENAMEVOL_NEW               1367
#define IDC_ADDFILES_CONVEOLNONE        1368
#define IDC_ADDFILES_CONVEOLTEXT        1369
#define IDC_ADDFILES_CONVEOLALL         1370
#define IDC_ADDFILES_STATIC4            1371
#define IDC_PROPS_CREATEWHEN            1372
#define IDC_EOLSCAN_CR                  1374
#define IDC_EOLSCAN_LF                  1375
#define IDC_EOLSCAN_CRLF                1376
#define IDC_EOLSCAN_CHARS               1377
#define IDC_PREF_PASTE_JUNKPATHS        1378
#define IDC_EXT_CONVEOLTYPE             1379
#define IDC_ADDFILES_CONVEOLTYPE        1380
#define IDC_TWOIMG_LOCKED               1381
#define IDC_TWOIMG_DOSVOLSET            1382
#define IDC_TWOIMG_DOSVOLNUM            1383
#define IDC_TWOIMG_COMMENT              1384
#define IDC_TWOIMG_CREATOR              1385
#define IDC_TWOIMG_VERSION              1386
#define IDC_TWOIMG_FORMAT               1387
#define IDC_TWOIMG_BLOCKS               1388
#define IDC_FVIEW_DATA                  1395
#define IDC_FVIEW_RSRC                  1396
#define IDC_FVIEW_CMMT                  1397
#define IDC_FVIEW_FORMATSEL             1399
#define IDC_FVIEW_FMT_HEX               1400
#define IDC_FVIEW_FMT_RAW               1401
#define IDC_FVIEW_FMT_BEST              1403
#define IDC_PDISK_OPENVOL_RO            1405
#define IDC_EOLSCAN_HIGHASCII           1407
#define IDC_CASSETTE_LIST               1414
#define IDC_IMPORT_CHUNK                1416
#define IDC_CASSETTE_ALG                1418
#define IDC_CASSETTE_INPUT              1419
#define IDC_CASSIMPTARG_FILENAME        1420
#define IDC_CASSIMPTARG_BAS             1421
#define IDC_CASSIMPTARG_INT             1422
#define IDC_CASSIMPTARG_BIN             1423
#define IDC_CASSIMPTARG_BINADDR         1424
#define IDC_CASSIMPTARG_RANGE           1425
#define IDC_CLASH_RENAME                1426
#define IDC_CLASH_SKIP                  1427
#define IDC_CLASH_WINNAME               1428
#define IDC_CLASH_STORAGENAME           1429
#define IDC_PREF_REDUCE_SHK_ERROR_CHECKS 1430
#define IDC_IMPORT_BAS_RESULTS          1431
#define IDC_IMPORT_BAS_SAVEAS           1432
#define IDC_FVIEW_FIND                  1438
#define IDC_CREATEFSHFS_VOLNAME         1440
#define IDC_PROPS_HFS_FILETYPE          1441
#define IDC_PROPS_HFS_AUXTYPE           1442
#define IDC_PROPS_HFS_MODE              1444
#define IDC_PROPS_HFS_LABEL             1445
#define IDC_PASTE_SPECIAL_COUNT         1446
#define IDC_PASTE_SPECIAL_PATHS         1447
#define IDC_PASTE_SPECIAL_NOPATHS       1448
#define IDC_PROGRESS_COUNTER_COUNT      1449
#define IDC_PROGRESS_COUNTER_DESC       1450
#define IDC_PDISK_OPENVOL_PHYS0         1451
#define IDC_PREF_SHK_BAD_MAC            1453
#define IDS_READONLY                    2021
#define IDS_FAILED                      2023
#define IDS_ERROR                       2024
#define IDS_NOT_ALLOWED                 2025
#define IDS_WARNING                     2026
#define IDS_CANCELLED                   2027
#define IDS_SELECTED_COUNT              2041
#define IDS_SELECTED_COUNTS_FMT         2042
#define IDS_BLOCK                       2045
#define IDS_DEFILE_FIND_FAILED          2047
#define IDS_DEFILE_OPEN_FAILED          2049
#define IDS_DISKEDIT_NOREADTS           2057
#define IDS_DISKEDIT_NOREADBLOCK        2058
#define IDS_DISKEDIT_FIRDFAILED         2059
#define IDS_EXT_SELECTED_COUNT          2060
#define IDS_EXT_SELECTED_COUNTS_FMT     2061
#define IDS_INDIC_RSRC                  2062
#define IDS_INDIC_DISK                  2063
#define IDS_INDIC_COMMENT               2064
#define IDS_INDIC_DATA                  2065
#define IDS_NOW_ADDING                  2066
#define IDS_ADDING_AS                   2067
#define IDS_DEL_SELECTED_COUNTS_FMT     2068
#define IDS_DEL_SELECTED_COUNT          2069
#define IDS_DEL_ALL_FILES               2070
#define IDS_DEL_OK                      2071
#define IDS_DEL_TITLE                   2072
#define IDS_TEST_SELECTED_COUNTS_FMT    2073
#define IDS_TEST_SELECTED_COUNT         2074
#define IDS_TEST_ALL_FILES              2075
#define IDS_TEST_OK                     2076
#define IDS_TEST_TITLE                  2077
#define IDS_NOW_TESTING                 2078
#define IDS_MB_APP_NAME                 2079
#define IDS_NO_COMMENT_ADD              2080
#define IDS_EDIT_COMMENT                2081
#define IDS_DEL_COMMENT_OK              2082
#define IDS_RECOMP_SELECTED_COUNT       2083
#define IDS_RECOMP_SELECTED_COUNTS_FMT  2084
#define IDS_RECOMP_ALL_FILES            2085
#define IDS_RECOMP_OK                   2086
#define IDS_RECOMP_TITLE                2087
#define IDS_NOW_EXPANDING               2088
#define IDS_NOW_COMPRESSING             2089
#define IDS_PRINT_CL_JOB_TITLE          2090
#define IDS_REG_EXPIRED                 2091
#define IDS_REG_FAILURE                 2092
#define IDS_REG_INVALID                 2093
#define IDS_REG_EVAL_REM                2094
#define IDS_REG_BAD_ENTRY               2095
#define IDS_OPEN_AS_NUFX                2096
#define IDS_ABOUT_UNREGISTERED          2097
#define IDS_CDESC_140K                  2098
#define IDS_CDESC_800K                  2099
#define IDS_CDESC_BLOCKS                2100
#define IDS_CDEC_140K_13                2101
#define IDS_BAD_SST_IMAGE               2102
#define IDS_NIBBLE_TO_SECTOR_WARNING    2103
#define IDS_CDEC_RAWNIB                 2104
#define IDS_DISKEDITMSG_EMPTY           2105
#define IDS_DISKEDITMSG_SPARSE          2106
#define IDS_DISKEDITMSG_BADSECTOR       2107
#define IDS_DISKEDITMSG_BADBLOCK        2108
#define IDS_DISKEDITMSG_BADTRACK        2109
#define IDS_CONVFILE_SELECTED_COUNT     2110
#define IDS_CONVFILE_SELECTED_COUNTS_FMT 2111
#define IDS_CONVFILE_ALL_FILES          2112
#define IDS_CONVFILE_OK                 2113
#define IDS_CONVFILE_TITLE              2114
#define IDS_CONVDISK_SELECTED_COUNT     2115
#define IDS_CONVDISK_SELECTED_COUNTS_FMT 2116
#define IDS_CONVDISK_ALL_FILES          2117
#define IDS_CONVDISK_OK                 2118
#define IDS_CONVDISK_TITLE              2119
#define IDS_CONVDISK_SPACEREQ           2120
#define IDS_CDESC_40TRACK               2121
#define IDS_TRACKSTAR_TO_OTHER_WARNING  2122
#define IDS_DIFFERENT_NIBBLE_WARNING    2123
#define IDS_VOLUME_NO_REMOTE            2124
#define IDS_VOLUME_NO_CDROM             2125
#define IDS_VOLUME_NO_RAMDISK           2126
#define IDS_VOLUME_NO_GENERIC           2127
#define IDS_VOLUME_NO_CDRIVE            2128
#define IDS_VOLUME_SELECT_ONE           2129
#define IDS_OPERATION_CANCELLED         2130
#define IDS_NOT_READY                   2131
#define IDS_ASPI_NOT_LOADED             2132
#define IDS_NOW_DELETING                2133
#define IDS_VALID_FILENAME_PRODOS       2134
#define IDS_VALID_FILENAME_DOS          2135
#define IDS_VALID_FILENAME_PASCAL       2136
#define IDS_VALID_VOLNAME_PRODOS        2137
#define IDS_VALID_VOLNAME_DOS           2138
#define IDS_VALID_VOLNAME_PASCAL        2139
#define IDS_CLIPBOARD_REGFAILED         2140
#define IDS_CLIPBOARD_OPENFAILED        2141
#define IDS_CLIPBOARD_NOITEMS           2142
#define IDS_CLIPBOARD_ALLOCFAILED       2143
#define IDS_CLIPBOARD_NOTFOUND          2144
#define IDS_CLIPBOARD_READFAILURE       2145
#define IDS_CLIPBOARD_WRITEFAILURE      2146
#define IDS_CLIPBOARD_WIN9XMAX          2147
#define IDS_PRINTER_NOT_USABLE          2148
#define IDS_NLIST_DATA_FAILED           2149
#define IDS_PROPS_DOS_TYPE_CHANGE       2150
#define IDS_FDI_TO_OTHER_WARNING        2151
#define IDS_VALID_VOLNAME_HFS           2152
#define IDS_VALID_FILENAME_HFS          2153
#define IDS_PASTE_SPECIAL_COUNT         2154
#define IDS_NO_FORKS_SPECIFIED          2155
#define IDM_FILE_NEW_ARCHIVE            40001
#define IDM_FILE_OPEN                   40002
#define IDM_FILE_CLOSE                  40003
#define IDM_FILE_PRINT                  40004
#define IDM_ACTIONS_ADD_FILES           40005
#define IDM_FILE_EXIT                   40006
#define IDM_ACTIONS_ADD_DISKS           40007
#define IDM_ACTIONS_EXTRACT             40008
#define IDM_ACTIONS_VIEW                40009
#define IDM_ACTIONS_TEST                40010
#define IDM_ACTIONS_DELETE              40011
#define IDM_EDIT_SELECT_ALL             40014
#define IDM_ACTIONS_INVERT_SELECTION    40015
#define IDM_EDIT_PREFERENCES            40016
#define IDM_HELP_CONTENTS               40017
#define IDM_HELP_ORDERING               40018
#define IDM_HELP_ABOUT                  40019
#define IDM_ACTIONS_RECOMPRESS          40020
#define IDM_SORT_PATHNAME               40025
#define IDM_SORT_TYPE                   40026
#define IDM_SORT_AUXTYPE                40027
#define IDM_SORT_MODDATE                40028
#define IDM_SORT_FORMAT                 40029
#define IDM_SORT_SIZE                   40030
#define IDM_SORT_RATIO                  40031
#define IDM_SORT_PACKED                 40032
#define IDM_SORT_ACCESS                 40033
#define IDM_SORT_ORIGINAL               40034
#define IDM_CONVERT_TOBSC               40039
#define IDM_CONVERT_FROMBSC             40040
#define ID_INDICATOR_COMPLETE           40043
#define IDM_TOOLS_DISKEDIT              40044
#define IDM_HELP_WEBSITE                40046
#define IDM_EDIT_INVERT_SELECTION       40048
#define IDM_ACTIONS_RENAME              40050
#define IDM_ACTIONS_EDIT_COMMENT        40051
#define IDM_TOOLS_DISKCONV              40054
#define IDM_TOOLS_SST_MERGE             40055
#define IDM_ACTIONS_OPENASDISK          40063
#define IDM_ACTIONS_EDIT_PROPS          40064
#define IDM_ACTIONS_CONV_DISK           40065
#define IDM_ACTIONS_CONV_FILE           40066
#define IDM_TOOLS_BULKDISKCONV          40067
#define IDM_FILE_OPEN_VOLUME            40068
#define IDM_TOOLS_IMAGECREATOR          40072
#define IDM_TOOLS_VOLUMECOPIER_FILE     40074
#define IDM_TOOLS_VOLUMECOPIER_VOLUME   40075
#define IDM_FILE_ARCHIVEINFO            40079
#define IDM_ACTIONS_CREATE_SUBDIR       40080
#define IDM_ACTIONS_RENAME_VOLUME       40081
#define IDM_TOOLS_EOLSCANNER            40083
#define IDM_FILE_FLUSH                  40084
#define IDM_FILE_SAVE                   40085
#define IDM_EDIT_COPY                   40086
#define IDM_EDIT_PASTE                  40087
#define IDM_TOOLS_TWOMGPROPS            40088
#define IDM_TOOLS_TWOIMGPROPS           40089
#define IDM_ACTIONS_CONV_TOWAV          40094
#define IDM_ACTIONS_CONV_FROMWAV        40095
#define IDM_ACTIONS_IMPORT_BAS          40097
#define IDM_FILE_REOPEN                 40098
#define IDM_EDIT_FIND                   40100
#define IDM_EDIT_PASTE_SPECIAL          40101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         40102
#define _APS_NEXT_CONTROL_VALUE         1455
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
